# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-BT-PhoneBill
version:      1.00
version_from: lib/Data/BT/PhoneBill.pm
installdirs:  site
requires:
    Date::Simple:                  0
    IO::File:                      0
    Test::More:                    0.17
    Text::CSV_XS:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
